#! /bin/bash

RANGE="$1"

SCRIPTNAME="$(basename "$0")"
if [ -z "$RANGE" ] ; then
    echo "$SCRIPTNAME: Range not specified" >&2
    echo "Usage: $SCRIPTNAME RANGE" >&2
    exit 1
fi

SCRIPTDIR="$(dirname "$0")"

INBOX="$("${SCRIPTDIR}/scandir" inbox)"
ISOS="$("${SCRIPTDIR}/scandir" isos)"
LABEL="paper-archive-b${RANGE}"
CATALOGUE="${ISOS}/${LABEL}.list"
ISONAME="${LABEL}.iso"

"$SCRIPTDIR/lsbatch" "$RANGE" | while read batch ; do
    echo "$(basename "$batch")=${batch}"
done > "$CATALOGUE"

genisoimage -V "$LABEL" -J -r -o "${ISOS}/${ISONAME}" -graft-points -path-list "$CATALOGUE"
cd "$ISOS"
sha1sum "$ISONAME" > "$ISONAME.sha1"
