#! /bin/bash

RANGE="$1"

SCRIPTNAME="$(basename "$0")"
if [ -z "$RANGE" ] ; then
    echo "$SCRIPTNAME: Range not specified" >&2
    echo "Usage: $SCRIPTNAME RANGE" >&2
    exit 1
fi

SCRIPTDIR="$(dirname "$0")"

INBOX="$("${SCRIPTDIR}/scandir" inbox)"
ISOS="$("${SCRIPTDIR}/scandir" isos)"
LABEL="paper-archive-b${RANGE}"
CATALOGUE="${ISOS}/${LABEL}.list"
ISONAME="${LABEL}.iso"

function generate-catalogue() {
    "$SCRIPTDIR/lsbatch" "$RANGE" | while read batch ; do
        echo "$(basename "$batch")=${batch}"
    done
    echo "batch_index.txt=$INBOX/batch_index.txt"
}

generate-catalogue > "$CATALOGUE"

genisoimage -quiet -V "$LABEL" -J -r -o "${ISOS}/${ISONAME}" -graft-points -path-list "$CATALOGUE" || exit 3
cd "$ISOS" || exit 4
sha1sum "$ISONAME" > "$ISONAME.sha1" || exit 4
ln -sf "$ISOS/$ISONAME" "$ISOS/${ISONAME}.sha1" "${HOME}/Desktop/"
echo "$ISONAME"
