#!/usr/bin/env perl


use v5.10;
use strict;
use warnings;

use FindBin qw/$RealBin/;
use lib File::Spec->catfile($RealBin, 'lib');

use LazyScan qw/scanhome/;

say File::Spec->catfile(scanhome(), @ARGV);

=head1 NAME

scanhome - print the scan base directory to STDOUT

=head1 USAGE

    scanhome [PATHS ...]

=head1 DESCRIPTION

Exposes L<LazyScan::scanhome> function as a shell command.
As a bonus, uses File::Spec to join further PATHS specified as args onto the end.

=head1 EXAMPLES

    $ scanhome
    /home/user/scan

    $ scanhome inbox
    /home/user/scan/inbox

    $ SCANHOME=/foo scanhome inbox
    /foo/inbox

=cut
