#!/usr/bin/env perl


use v5.10;
use strict;
use warnings;

use FindBin qw/$RealBin/;
use lib File::Spec->catfile($RealBin, 'lib');

use LazyScan qw/scandir/;

say File::Spec->catfile(scandir(), @ARGV);

=head1 NAME

scandir - print the scan base directory to STDOUT

=head1 USAGE

    scandir [PATHS ...]

=head1 DESCRIPTION

Exposes L<LazyScan::scandir> function as a shell command.
As a bonus, uses File::Spec to join further PATHS specified as args onto the end.

=head1 EXAMPLES

    $ scandir
    /home/user/scan

    $ scandir inbox
    /home/user/scan/inbox

    $ SCANHOME=/foo scandir inbox
    /foo/inbox

=cut
